const cat = {
  antiqueDohiya:"antiqueDohiya",
  antiqueLucky:"antiqueLucky",
  antiqueMala:"antiqueMala",
  antiqueSet:"antiqueSet",
  ringsForWomen:"ringsForWomen",
  braceletsForMen:"braceletsForMen",
  LuckyForMen:"LuckyForMen",
  ringsForMen:"ringsForMen",
  bangles:"bangles",

  earrings:"earrings",

  rings:"rings",
};
export const categories = [
  {
    _id: 1001,
    name: "Antique Dohiya",
    image: "https://i.postimg.cc/qM2TPsjY/Nk-Pnoxz7-JOS3-Vk-Fx-UW3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "antiqueDohiya",
  },
  {
    _id: 1002,
    name: "Antique Lucky",
    image: "https://i.postimg.cc/9FCQmXzJ/Nopux-YZjglg-KFee0f04.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "antiqueLucky",
  },

  {
    _id: 1003,
    name: "Antique Mala",
    image: "https://i.postimg.cc/hv40LzKp/O0rrscs-3fi2-Hzw-Ux-Nz.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "antiqueMala",
  },

  {
    _id: 1004,
    name: "Antique Set",
    image: "https://i.postimg.cc/0QMyjxMj/O0rqa-Eo-Fs-Qk6-PYba-Kt-F.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "antiqueSet",
  },
  {
    _id: 1005,
    name: "Bangles",
    image: "https://i.postimg.cc/zX84jB29/Ns-Nnk6-Rkko-Yi-DPB8-TZF.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "bangles",
  },
  {
    _id: 1006,
    name: "Women's Rings",
    image: "https://i.postimg.cc/VkVjmnDy/Nsgx-FKxc-Zp-JYv7kbdc-C.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "ringsForWomen",
  },
  
  {
    _id: 1007,
    name: "Men's Bracelets",
    image: "https://i.postimg.cc/k4ZhKQhm/O-AJjtd-Gvjwwhq0-C3a-R.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "braceletsForMen",
  },
  {
    _id: 1008,
    name: "Men's Lucky",
    image: "https://i.postimg.cc/W4fbn5Kd/O0s-Aanhqrok-S5-YJBRuf.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "LuckyForMen",
  },
  {
    _id: 1009,
    name: "Men's Rings",
    image: "https://i.postimg.cc/FHVmKhQb/Ns-S4h-LKprk6-2-OJMVso.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "ringsForMen",
  },
  

  
];


export const EaringHead =[
  {
    _id: 6001,
    name: "Earrings",
    image: "https://i.postimg.cc/BnLkpQK3/O4trfc-Kgbuatk-PAy-G7-V.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "earrings",
  },
  // {
  //   _id: 6001,
  //   name: "Studs",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "earrings",
  // },
  // {
  //   _id: 6002,
  //   name: "Hoops",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "earrings",
  // },
  // {
  //   _id: 6003,
  //   name: "Dangles",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "earrings",
  // },
];
export const RingsHead =[
  {
    _id: 7001,
    name: "Engagement Rings",
    image: "https://i.postimg.cc/Y97zP1VT/3340-XMens-ring.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "ring",
  },
  // {
  //   _id: 7002,
  //   name: "Wedding Bands",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "ring",
  // },
  // {
  //   _id: 7003,
  //   name: "Fashion Rings",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "ring",
  // },
];

export const DigitalGold =[
  {
    _id: 8001,
    name: "Invest in Gold",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "digitalGold",
  },
  {
    _id: 8002,
    name: "Gold Savings",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "digitalGold",
  },
  {
    _id: 8003,
    name: "Gold Loans",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "digitalGold",
  },
];
export const Collections =[
  {
    _id: 9001,
    name: "Festive Collection",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "collections",
  },
  {
    _id: 9002,
    name: "Bridal Collection",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "collections",
  },
  {
    _id: 9003,
    name: "Casual Collection",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "collections",
  },
];
export const weddings =[
  {
    _id: 10001,
    name: "Bridal Jewellery",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "wedding",
  },
  {
    _id: 10002,
    name: "Groom's Jewellery",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "wedding",
  },
  {
    _id: 10003,
    name: "Wedding Gifts",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "wedding",
  },
];
export const more =[
  
  
  {
    _id: 10003,
    name: "Gifts",
    image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "gift",
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "New Deals",
    title: "At low price",
    buttonTitle: "Browse Deals",
    image: "https://i.postimg.cc/Y97zP1VT/3340-XMens-ring.webp",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "New Necklace",
    title: "From $40.00",
    buttonTitle: "Shop Necklace",
    image: "https://i.postimg.cc/QM8MnCm0/Necklace-X12-980.webp",
    _base: "/category/powerTools",
    color: "#ffffff",
  },
  {
    _id: 3003,
    name: "New Bangles",
    title: "From $40.00",
    buttonTitle: "Shop Now",
    image: "https://i.postimg.cc/FHgRZ3yY/Bangels-X45-930.webp",
    _base: "/product",
    color: "#ffffff",
  },
];

export const shopByEmotion = [
  {
    _id: 40001,
    image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
    title: "iPhone 15 rear camera design will be available",
    _base: "Technology",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 40002,
    image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
    title: "Setup your surround sound speaker",
    _base: "Samrt thing",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 40003,
    image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
    title: "Hook up a receiver for your home theater",
    _base: "Life style",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
];

export const products = [
  // {
  //   _id: 2001,
  //   name: "Antique Dhohiya",
  //   images: [
  //     "https://i.postimg.cc/BbWzpy9v/Nk-Pns7-C97k-Jd-Zj-HMw-R.jpg",
  //     // "https://i.postimg.cc/Y97zP1VT/3340-XMens-ring.webp",
  //     // "https://i.postimg.cc/k4tDWZfm/Mensringx3-630.webp",
  //     // "https://i.postimg.cc/430m7ZvP/Mensring-X3-680.webp",
      
  //   ],
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
  //   regularPrice: 600,
  //   discountedPrice: 580,
  //   quantity: 1,
  //   rating: 4.5,
  //   reviews: 50,
  //   category: "Ring",
  //   colors: ["red", "blue", "green", "yellow", "black", "white"],
  //   brand: "Samsung",
  //   isStock: true,
  //   overView: "Blutooth Speaker",
  //   isNew: true,
  //   _base: cat?.antiqueDohiya,
  // },
  
  {
    _id: 2001,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/qM2TPsjY/Nk-Pnoxz7-JOS3-Vk-Fx-UW3.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2002,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/BbWzpy9v/Nk-Pns7-C97k-Jd-Zj-HMw-R.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2003,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/7ZPWK0cS/Nm4v2-G8-QS9q7-Tx-DJI8u.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2004,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/ZKxQPVfT/Nm4v2u986c-Whp7h7l-WU.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2005,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/wB7bpH9v/Nm4v-CL662-XPYky-W5-O-l.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2006,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/9QzB4pKg/Nm4v-Eg-Q4-E-u-AKagh-NTK.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2007,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/sxcJW03q/Nm-Vm-I9d6-DE-Ug-Kv-YQa.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2008,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/gcqs1r3s/Nozx-Oui-Hx-I-8e-DFgq-Xf.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2009,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/m2Lj4Rws/Nozx-RNBnc-CY2-Jr-Znkqc.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2010,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/yxYZM6zp/O6j9i9f6-98vpi-CAfgn.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  {
    _id: 2011,
    name: "Antique Dhohiya",
    images: [
      "https://i.postimg.cc/50JvmqKV/O6j-A1-Ojtz6-Qggra-Jh-Vh.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Dhohiya",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueDohiya,
  },
  

  {
    _id: 2012,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/9FCQmXzJ/Nopux-YZjglg-KFee0f04.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2013,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/JzyVmS3p/Nozx-Oej-Lwd6-Hs-FPEg-OC.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2014,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/6pDsQzYt/Nq7-BAe-3w-WWi4-Zha6-Mi.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2015,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/1tQLGtkd/Nq-H9er-Fn-ZS3ang-Fm3f-J.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2016,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/TwJBCxG3/Nq-H9f3l1evr-OI9-Xp7-TK.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2017,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/tJ7DWG4f/Nr5f-Tb-Y3-J7v-L7ffrv7n.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2018,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/Hsq3cKDZ/Nr5f-X1l-KVPNNg-CJOEX9.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2019,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/ZKdxScBr/Nr5f-Xaf-BLlq2yh0h-Ad-M.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2020,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/g2bqkZ81/Nr5f-XJ3-Qz-Cjl-L5b4cb3.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2021,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/1t8JNZtd/Nr5f-YQu-EF-kfxb-ZPa-B.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2022,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/RCngS926/Nr5kohdkbz-OMI-2zoc-C.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2023,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/gJp2xGNz/Nr-Ay-Pfjfli-ATu-Uvyp7.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2024,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/vBvH9CNW/Nr-Ay-PO1-AXv-yvn-UTxo7.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2025,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/TPgP2KjN/Nr-Ay-Q11ru-Dfrt-Luo0-Da.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2026,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/44Bx3ktG/Nr-Ay-QMm-R6c0rqn-Aav-Mr.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2027,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/4yhLjTRc/Nre5bh-L2-Zhg-HLQgkvf-C.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2028,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/W3QLd82M/Nre5p-WS09lir-Aic2-Fnx.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2029,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/PfgTJXxB/Nre6cnl-Hq2q4-AYwvsu-N.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2030,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/x1YQG6L5/Nre6jl-Xtp7q-Mh-JLLRQl.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2031,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/qMwbYw9j/Nre6-P5-Pm-MC90-Yvb-F3-E4.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2032,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/mrzmPsh5/Nre6yw88rv-g-REwfc-VC.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2033,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/fbGBXr9T/Nre7-Ai0-ZSx-Ipz-JBlm-Ib.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2034,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/6qwcb4ck/Nre7-Lv-O6e1cg2ptao-BK.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2035,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/dV72B9v7/Nre7-T71-Xmd-Si-Vp-OWh7.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2036,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/X7YcZbzk/Nsgwh5-Z0-Ki1nw-Kxb0v.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2037,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/0j2mJYcy/Nt-Ydv-Ix-Se7jd-LZn-D7-L.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2038,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/3NSGjkcC/Nx-Gi-IUZym4m-NEt-IUrk.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2039,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/MG7jPPLG/Nxl-sb-Bo1-WZWni-Eo-B0-A.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2040,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/TwQ5GyfM/Nzc-QQDuxn-OHIY5-ODi-MM.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2041,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/x84kJWX6/Nzc-QQV6h-F6un0o7-MZJ9.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  {
    _id: 2042,
    name: "Antique Lucky",
    images: [
      "https://i.postimg.cc/66j4mGMC/Nzc-QQy-EZUyw-Ce-vvm-S4.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Lucky",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueLucky,
  },
  
  {
    _id: 2043,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/hv40LzKp/O0rrscs-3fi2-Hzw-Ux-Nz.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2044,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/pdY8sWG7/O0rrss-Sg-RCDrig0h58n.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2045,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/JzXjBcbR/O0rrtf-D3-Bt9z9ico3k-S.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2046,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/xdSMGJRM/O0rrtq-IDBuk4-K5-NLq-Hs.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2047,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/ZYfPkqbz/O0rrukf81-HGmm-Oz7r-GC.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2048,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/Kj4McnGS/O0rrv-As4j9k5c-JP8-DJy.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2049,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/7LDJJvHN/O0rrv-MDggopke-Oz7-GFn.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2050,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/d1V7n8Tk/O0rrvr-Ld-Tceb-Pm-N0zs0.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2051,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/Ss1nPJWZ/O0rrv-X161-KOc9ovl-Jq-Y.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2052,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/fRQJ149h/O0rrw18qgz-Q4-Tvli-TXl.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2053,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/nLRmyRxY/O0rrw-Xk9ly-Cw-ITOwyeq.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2054,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/tJPVV9x2/O0rrx8ho-N6-Tl-RPy-IUQx.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2055,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/KzCMz1R1/O0rrx-UMs-T1-EP3i-Kk-Tr-P.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  {
    _id: 2056,
    name: "Antique Mala",
    images: [
      "https://i.postimg.cc/3wJpbMsx/O0rrz5-Pjzu-YX7-Eh05ks.jpg",
    ],
    description: "NA",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Antique Mala",
    colors: ["Gold"],
    brand: "NA",
    isStock: true,
    overView: "NA",
    isNew: true,
    _base: cat?.antiqueMala,
  },
  

  {
    "_id": 2057,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/0QMyjxMj/O0rqa-Eo-Fs-Qk6-PYba-Kt-F.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2058,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/Kj3k6Br9/O0rqasua-BQd-Ov-2-QCst.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2059,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/BQDNDK9c/O0rqb-KZwe-GHz-ylrt-TB.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2060,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/qBN1JF1F/O0rqbm-Rw-H3kss3-AUy-Qf.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2061,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/cLShcLdq/O0rqb-Yr-Rzvloesii-N0.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2062,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/xCD1XhKP/O0rqcsl-KUGl-E0zq-Va-Og.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2063,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/L6HhkcGC/O0rqd3-H-yko44vcnx4g.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2064,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/Dw0ZHqv1/O0rqd-Fu-RXF1-Vl-WTwnb-K.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2065,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/7hXHQLjB/O0rqds-GXq-BQGSq-Tp-K5-F.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2066,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/rp6kjWKV/O0rqf-Yg-Oun-Vh-TAa4s-h.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2067,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/Cx8yR1JW/O0rqg33w-Kx-Imuty-k-Mg.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2068,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/bNWcYb0x/O0rqh4-FFi8l-Db-TCSb9-Z.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  {
    "_id": 2069,
    "name": "Antique Set",
    "images": [
      "https://i.postimg.cc/vH1kKTRc/O0rqhbmq-Dwqibe9-Py-H.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Antique Set",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.antiqueSet
  },
  
  {
    "_id": 2070,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/zX84jB29/Ns-Nnk6-Rkko-Yi-DPB8-TZF.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2071,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/nzjfycyn/Ns-Wkzp-Wl-HROa5yo-GD1h.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2072,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/k4ZhKQhm/O-AJjtd-Gvjwwhq0-C3a-R.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2073,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/1Xq7H8LN/O-AJl5-Vop-Ls-Nqe-CHXsm.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2074,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/28nXLBQs/O-AJo-Qh9-N4v-Czqp-GGNs.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2075,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/DwngHj9Z/O-AJYiq-J-6zj-CPblb5e.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2076,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/9QZ6tnGQ/O-AJZ1-HIUg-L4-Y3nu-AD.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2077,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/ry5wsQHM/O-AJZOCIJ9-P29-N0a-Dy9.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2078,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/s2Bw4QF9/O-AJ-1h-P2ad-Zrk-Co-Nec.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2079,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/WbCBLv2n/O0r-TWG38-RGVv-WWJmk-K.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2080,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/MZbHp9cV/O0-SQr5-Iqw-Kt9621tz-Ho.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2081,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/CKV95snn/O0-SQv-Opji-Rv-JS3-I1-Zq.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2082,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/nryfkbr0/O5r-Jltxb-J2-Kk5p-VR63.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2083,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/YC1bn4b1/O5r-Jmc9-Lza-PMB6g-O3-Cw.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2084,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/W3Sy9Dp9/O6f6-QSHo-QFm-AJn-ZIBxn.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2085,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/90bJmswJ/O6f6-Qy-Yh5-N5-L3oe-X4al.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2086,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/nzsd135L/O6-Kq-VBUy-Ih-ES6-WOb-Rh8.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2087,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/26P094R7/O6-QRKVy9-VQXuuz3-B1b.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2088,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/3JQLgCZK/O6yi-KCw5-VGg56-R91j1.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2089,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/mrkVbdTS/O6yi-KXp-QG0-Ps1-JEAe-Pj.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2090,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/x10tZf7h/O7-Dl-RGTno-Sh-NGg-dvg-D.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  {
    "_id": 2091,
    "name": "Bangles",
    "images": [
      "https://i.postimg.cc/zBRjhVbb/O9t-M91n-I2b-Jf-NKi-L-c-A.jpg"
    ],
    "description": "NA",
    "regularPrice": 220,
    "discountedPrice": 210,
    "quantity": 1,
    "rating": 4.5,
    "reviews": 90,
    "category": "Bangles",
    "colors": ["Gold"],
    "brand": "NA",
    "isStock": true,
    "overView": "NA",
    "isNew": true,
    "_base": cat?.bangles
  },
  
  
    {
      "_id": 30001,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/VkVjmnDy/Nsgx-FKxc-Zp-JYv7kbdc-C.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30002,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/J0psKCFw/Nsgx-Fs-Eze6-EYniz-O83-R.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30003,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/gcsLG32M/Nsgx-GQTu-n-Votc0ba5t.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30004,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/8PCJcsFT/Nsgx-Gsu6-Iug27p-Pe-HAQ.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30005,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/J4dykmJZ/Nsgx-HJmuk-Rn-Mg-K1gm-E.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30006,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/Kv4jFVVz/Nsgx-KWTr-Pee-Sv2x-Tt-L9.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30007,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/bNMJvgcR/Nsgx-NXNKa-L8-FNLe-Xl-TS.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30008,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/MZ9HCx9N/Ns-Nte-JXdy-YUZko-Ue-Rs-H.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30009,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/1X3t8Y3v/Ns-Nthdk-TOJClzu4ek7g.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30010,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/fR9bSdMQ/Ns-Nth-Lw2-Et-U130cv-Fu-T.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30011,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/T2N2k0wX/Ns-Nti-E6n-Lw25m-B-Pom-W.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30012,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/T2N2k0wX/Ns-Nti-E6n-Lw25m-B-Pom-W.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30013,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/7YpH4L0s/Ns-Ntm-Ju-TVVDr-Gdc-Oom-P.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30014,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/HkXpkCtp/Ns-Ntm-Vtq3d-LB7-V-gn-NQ.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30015,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/yxgMpFQV/Ns-Nto-72-O5-Xdw-Q8-NFy.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30016,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/xd9SjNCR/Ns-Ntr-Ojsz-ES03p-He23-T.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30017,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/mkKsTdzz/Ns-Nts-Ntjc-FXw-H03-CC0u.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
    {
      "_id": 30018,
      "name": "Women's Rings",
      "images": [
        "https://i.postimg.cc/pVmyM43d/Ns-Ntu-Ja-AH5-OWt-FOYI60.jpg"
      ],
      "description": "NA",
      "regularPrice": 220,
      "discountedPrice": 210,
      "quantity": 1,
      "rating": 4.5,
      "reviews": 90,
      "category": "Women's Rings",
      "colors": ["Gold"],
      "brand": "NA",
      "isStock": true,
      "overView": "NA",
      "isNew": true,
      "_base": cat?.ringsForWomen
    },
  
    
      {
        "_id": 4001,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/k4ZhKQhm/O-AJjtd-Gvjwwhq0-C3a-R.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4002,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/1Xq7H8LN/O-AJl5-Vop-Ls-Nqe-CHXsm.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4003,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/28nXLBQs/O-AJo-Qh9-N4v-Czqp-GGNs.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4004,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/DwngHj9Z/O-AJYiq-J-6zj-CPblb5e.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4005,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/9QZ6tnGQ/O-AJZ1-HIUg-L4-Y3nu-AD.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4006,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/ry5wsQHM/O-AJZOCIJ9-P29-N0a-Dy9.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4007,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/s2Bw4QF9/O-AJ-1h-P2ad-Zrk-Co-Nec.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4008,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/zBRjhVbb/O9t-M91n-I2b-Jf-NKi-L-c-A.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
      {
        "_id": 4009,
        "name": "Men’s Bracelets",
        "images": [
          "https://i.postimg.cc/y6rZkdxh/O-AJif342fy-VBe9-G4-I3.jpg"
        ],
        "description": "NA",
        "regularPrice": 220,
        "discountedPrice": 210,
        "quantity": 1,
        "rating": 4.5,
        "reviews": 90,
        "category": "Men’s Bracelets",
        "colors": ["Gold"],
        "brand": "NA",
        "isStock": true,
        "overView": "NA",
        "isNew": true,
        "_base": cat?.braceletsForMen
      },
    
      
        {
          "_id": 101,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/jd8YVDxf/O98k-Ulyiw9w96-HORBK4.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
        {
          "_id": 102,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/mkbJJsKV/O98u-Jf4g-0-Koprkr-GFx.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
        {
          "_id": 103,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/1RHL68Nd/O98u-JPa94-CSam6-Igr6-P.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
        {
          "_id": 104,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/QdRPs5RF/O98u-KCUFl-I-t1-M6te-M4.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
        {
          "_id": 105,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/qvtY9QZf/O98v6-Uyi-New-CQ94-Fj-Y.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
        {
          "_id": 106,
          "name": "Men's Lucky",
          "images": [
            "https://i.postimg.cc/50mkwrjz/O9hem8w-GHwc-Em3c-WNo8.jpg"
          ],
          "description": "NA",
          "regularPrice": 220,
          "discountedPrice": 210,
          "quantity": 1,
          "rating": 4.5,
          "reviews": 90,
          "category": "Men's Lucky",
          "colors": ["Gold"],
          "brand": "NA",
          "isStock": true,
          "overView": "NA",
          "isNew": true,
          "_base": cat?.LuckyForMen
        },
      
        
          {
            "_id": 202,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/FHVmKhQb/Ns-S4h-LKprk6-2-OJMVso.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 203,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/tJ6GGj5x/Ns-S4-Kfh-TPi4l2e-KU219.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 204,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/FFk4Ly4H/Ns-S4-KLu-UVQh-Tot-EW-a.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 205,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/9MKHkMG2/Ns-S4l9-KXet-Eh8su-LRSH.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 206,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/1tfZM6VM/Ns-S4m-bgb-Lya-HIqm-P0x.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 207,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/wTKdc1qc/Ns-S4-NMi46-AAQU-l-WW0z.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 208,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/HkdDRF7r/Ns-S4rgmq2-R8-Vkp-TD2-Eq.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 209,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/HkzDg3QB/Ns-S4tnmydd3-By-Fls-SN.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 210,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/QMMLx5ms/Ns-S50e-i-LY-CCq-S3ol-B.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 211,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/YSD549DF/Ns-S50tvt0-QXi-RGdg-Y4f.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 212,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/76pjVRkY/Ns-S51-Knc349x-C9q-VPA.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 213,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/Fz38nxrb/Ns-S51mg8ra-EAz-VEi6w-U.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
          {
            "_id": 214,
            "name": "Men's Rings",
            "images": [
              "https://i.postimg.cc/ZYdGRJ89/Ns-S53-Kyqp-Z818gx-Sk-M0.jpg"
            ],
            "description": "NA",
            "regularPrice": 220,
            "discountedPrice": 210,
            "quantity": 1,
            "rating": 4.5,
            "reviews": 90,
            "category": "Men's Rings",
            "colors": ["Gold"],
            "brand": "NA",
            "isStock": true,
            "overView": "NA",
            "isNew": true,
            "_base": cat?.ringsForMen
          },
        
        
          
            {
              "_id": 301,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/BnLkpQK3/O4trfc-Kgbuatk-PAy-G7-V.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 302,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/9MWL6Wrr/O4trf-X-6-Wuq7-Jibng-Kg.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 303,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/MHLtfVtQ/O4trg3b-7-NQAw4a-Ivb4.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 304,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/qBD1FH0v/O4trguo3-BURJ3gib0-i.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 305,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/sxxw2wPz/O4trg-Xk-KEGDm4-Bs-QIa-Z.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 306,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/XqtcY37K/O4trh2f-Z2g5jui-GK01m.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 307,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/dQhfwV5y/O4trh-BSVNaf6-Ib-TA0-WN.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 308,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/FKFPqrf1/O4trhhh8-VDi-EOzierz-N.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 309,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/BnBYMLnd/O4trh-K1-Gg-AJth42xl8u.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 310,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/Wpq5xf4m/O4trhq-X0-Dj-Uu-XD9-SU-X.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 311,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/6ptz2Wfz/O4trh-RYR1-P96lx8i3-P.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 312,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/8P8ZGBF2/O4trj-Ch7-JLkpf-PBHt-G.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 313,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/Prm25pYP/O4trj6-Lfwv-YDxx-CLXv8.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 314,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/pd1B6Db1/O4trjmv-C-Jd8j-Z8-E4g8.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 315,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/mrrwjmqH/O4trj-PRCl-Mw-SWB3-Ra-Nj.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 316,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/Y9GxKht2/O4trk-DXyqq-Eq-UO15p-Oe.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 317,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/50hSxbtB/O4trk-Jyo-Ge-K5-P3-KLywz.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
            {
              "_id": 318,
              "name": "Earrings",
              "images": [
                "https://i.postimg.cc/fRzjWHMr/O4trk-w2ksat-5-Zq-CL.jpg"
              ],
              "description": "NA",
              "regularPrice": 220,
              "discountedPrice": 210,
              "quantity": 1,
              "rating": 4.5,
              "reviews": 90,
              "category": "Earrings",
              "colors": ["Gold"],
              "brand": "NA",
              "isStock": true,
              "overView": "NA",
              "isNew": true,
              "_base": cat?.earrings
            },
          
          
];
